name: frontend
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.12.3
  location: ^5.0.3
  http: ^1.1.0
  url_launcher: ^6.1.10
  cupertino_icons: ^1.0.8
  flutter_dotenv: ^5.0.2
  geolocator: ^14.0.2
  geocoding: ^2.0.5
  google_generative_ai: ^0.2.2
  sqflite: ^2.2.5           # Added for local SQLite database support
  path: ^1.8.3              # Added to help with file paths for SQLite

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/camps_india.json
    - assets/images/logo.png
    - assets/images/redx_logo.png
    - .env           # <-- Add this line to include the .env file
